ROKT/rokt-sdk-react-native

RoktSampleApp/.babelrc
RoktSampleApp/App.js
RoktSampleApp/android/app/build.gradle
RoktSampleApp/haul.config.js
RoktSampleApp/ios/RoktSampleApp.xcodeproj/project.pbxproj
RoktSampleApp/package.json
RoktSampleApp/utils/rokt-constants.js
RoktSampleApp/utils/text-utils.js

Added a form to example app with validation
Added haul bundler

Finalising sample app 

---

README.md
Rokt.Widget/README.md
Rokt.Widget/android/src/main/java/com/reactlibrary/RoktEmbeddedViewManager.java
Rokt.Widget/android/src/main/java/com/reactlibrary/RoktEmbeddedViewPackage.java
RoktSampleApp/android/app/build.gradle
RoktSampleApp/android/app/src/main/java/com/roktsampleapp/MainApplication.java

Renaming RoktEmbeddedView
Updating README
Fixing gradle to run android with new naming
Moving README to top level

RoktEmbeddedView

---

Rokt.Widget/android/build.gradle
Rokt.Widget/package.json

Pointing to roktsdk 3.3.3 which includes bug fixes for:
Multiple terms and conditions button on screen rotation
Button radius not showing correctly

Android bug fixes

---

.buildkite/pipeline.yml
docker-compose.yml

Created my own docker image which has java/node and android installed

Fix pipeline

---

RoktSampleApp/App.js
RoktSampleApp/android/app/src/androidTest/java/com/roktsampleapp/RoktWebViewUITest.java
RoktSampleApp/android/app/src/androidTest/java/com/roktsampleapp/TestUtils.java

Added Overlay test for RN Android
https://rokt.atlassian.net/browse/MP-1719

updated UI test viewName

---

README.md
Rokt.Widget/README.md
Rokt.Widget/package-lock.json
RoktSampleApp/README.md
RoktSampleApp/ios/RoktSampleAppUITests/RoktSampleAppUITests.swift
RoktSampleApp/package-lock.json

Updated the Readme.md for ReactNative sdk.
(https://rokt.atlassian.net/browse/EINT-33)

Eint 33 update readme 

---

Rokt.Widget/package-lock.json
Rokt.Widget/package.json
RoktSampleApp/package.json

Resolved the Security bot alerts due to hermes-engine and shell-quote libraries by updating the React and ReactNative version.

update RN version to 0.68.0

---

README.md
Rokt.Widget/README.md
RoktSampleApp/ios/RoktSampleAppUITests/RoktSampleAppUITests.swift

Fix for iOS integration test
https://rokt.atlassian.net/browse/EINT-235
UI Test

fix ios test

---

.circleci/config.yml
Rokt.Widget/README.md
Rokt.Widget/android/build.gradle
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/README.md
RoktSampleApp/android/build.gradle
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

- Updated Rokt Native sdk version to 3.9.0
- Change Rokt RN sdk version to 3.9.0 

updated rokt sdk version to 3.9.0

---

Rokt.Widget/android/build.gradle
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
RoktSampleApp/package-lock.json
RoktSampleApp/package.json

- updated android sdk to 3.9.1
- changed RN sdk to 3.9.1
https://rokt.atlassian.net/browse/EINT-431

Updated rokt sdk

---

README.md
RoktSampleApp/README.md

This PR lists the commands to run the RN project on an M1 Mac as well as some troubleshooting steps.
Fixes [EINT-36(https://rokt.atlassian.net/browse/EINT-36)]
Update README on additional step to run on M1 Mac.
Ran on a local M1 Mac

[EINT-36] Update README to describe steps to run on M1 Mac

---

RoktSampleApp/README.md

Quick updates to the RoktSampleApp iOS setup
Added troubleshooting steps to npm install and run ios sections
Setup and built sample app locally on ios simulator

Quick update readme ios setup

---

Rokt.Widget/android/build.gradle
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

Updating all SDKs to version 3.12.0
Updated android and ios sdk versions to 3.12.0
Updated react native sdk version to 3.12.0
Verified example app
- [] I have made corresponding changes to the documentation.

[MP-2013] Update sdk version to 3.12.0

---

Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock

This reverts commit 937dc9bb5b6984e71b53188488785c1fab5cf07c.
Temporarily revert the commit for a patch release. 
Revert commit

NoJira - Revert "Fix podspec including non source files"

---

Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

Release SDK version 3.12.1
https://user-images.githubusercontent.com/49017604/232681074-651a01fb-daf3-44ff-8fd5-268ed34af973.mov
Describe the tests that you ran to verify your changes.

update to version 3.12.1

---

.buildkite/pipeline.yml
Rokt.Widget/android/build.gradle
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

Fixing pipeline and updating to 3.14.1
Ran both sample apps and checked node_modules was actually updated

Update to 3.14.1

---

Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

Release ReactNative SDK version 3.14.2

update to version 3.14.2

---

Rokt.Widget/android/build.gradle
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

Update React Native SDK version to `3.15.0`
Fixes [MP-2323]
Version update

[MP-2323] - Update SDK version to `3.15.0`

---

Rokt.Widget/ios/RNRoktWidget.m
Rokt.Widget/ios/RoktEventManager.h
Rokt.Widget/ios/RoktEventManager.m
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/App.js
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package-lock.json
RoktSampleApp/package.json

URL callback updates to React Native
- Pointed RN SDK to iOS SDK 3.16.0 alpha version
- Added `OpenURL` event to RCTEventEmitter
- Registered new `urlListener` and its callback `onOpenUrl` to forward to event emitter
- Added `OpenURL` event listener to sample app for testing
Tested locally in sample app. OpenURL event is triggered with `urlId` and `urlString` parameters
https://github.com/ROKT/rokt-sdk-react-native/assets/122853726/40d1b5ec-b458-4862-abf1-10ff1c89f260

add url callback to sdk and sample app

---

Rokt.Widget/ios/RNRoktWidget.m
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package-lock.json
RoktSampleApp/package.json

Update version and make description to optional
- Updated alpha version syntax to follow convention
- Updated description parameter in error to nullable
Tested with null description and verified diagnostic still sends with empty string

update alpha version and make description optional

---

Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/src/rokt-embedded-view.ios.tsx
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/ios/RoktSampleApp.xcodeproj/project.pbxproj
RoktSampleApp/package.json

Fix the issue when corner radius not affected for RactNative-iOS.
Fixes [([issue](https://rokt.atlassian.net/browse/MP-2478))]
White background removed from the iOS placeholder.
Before:
After

change background color to transparent

---

Rokt.Widget/android/build.gradle
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

Updating to 3.15.4
Fixes [MP-2577]
Updated all versions to 3.15.4
Ran both sample apps

[MP-2577] Update to 3.15.4

---

Rokt.Widget/android/build.gradle
Rokt.Widget/package.json
RoktSampleApp/package.json

Update the Android SDK version to 3.15.5
Fixes [MP-2667](https://rokt.atlassian.net/browse/MP-2667)
Version update

MP-2667 - Update Android SDK version to 3.15.5

---

Rokt.Widget/src/index.tsx

Fixing remaining types.
- Added | null to placeholders number
- Changed setFulfillmentAttributes to use Record
Typescript file

[NO-JIRA] Change types

---

Rokt.Widget/package-lock.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/android/build.gradle
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/ios/RoktSampleApp.xcodeproj/project.pbxproj

Updated iOS SDK version to 4.0.0-alpha.4 and increment compile and target SDK version for Android in Sample App.
Fixes [(No-JIRA)]

update iOS Rokt SDK version

---

.buildkite/bin/create_tag.sh
.buildkite/bin/extract_dist_tag.sh
.buildkite/bin/update_sample_app.sh
.buildkite/bin/update_versions.sh
.buildkite/release.pipeline.yml
Rokt.Widget/README_PUBLISHING.md
RoktSampleApp/android/fastlane/Fastfile

Adding pipeline to 4.0.x branch
cherry picked from commit 6dca841aa728c3d7e279e7bdd72f5f53110ceba5
Fixes [MP-2598]
Adding pipeline

[MP-2598] Automated Pipeline 4.0.x

---

.buildkite/release.pipeline.yml

Release pipeline was missing line to create index file for 4.0.x
- Added missing line

[NO-JIRA ] Add index file creation

---

.buildkite/pipeline.yml
.buildkite/release.pipeline.yml
README.md
Rokt.Widget/.eslintignore
Rokt.Widget/README.md
Rokt.Widget/app.plugin.js
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
Rokt.Widget/plugin/src/withRoktSDK.ts
Rokt.Widget/plugin/tsconfig.json
RoktSampleApp/package.json

Integrated Expo Config Plugin to allow SDK to be integrated with EXPO Custom Development Client Apps.
Fixes [([issue](https://rokt.atlassian.net/browse/MP-2292))]

MP-2292 Expo Config Plugin

---

Rokt.Widget/android/build.gradle
Rokt.Widget/android/src/main/java/com/reactlibrary/RNRoktWidgetModule.java
Rokt.Widget/ios/RNRoktWidget.m
Rokt.Widget/package-lock.json
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/ios/RoktSampleApp.xcodeproj/project.pbxproj

This PR is to record ReactNative as framework type for Metrics.
Fixes [([issue](https://rokt.atlassian.net/browse/MP-2636))]

MP-2636 Record ReactNative Plugin

---

RoktSampleApp/android/build.gradle
RoktSampleApp/android/gradle.properties

* Disable Jetifier https://issuetracker.google.com/issues/294342862
* Update the compile SDK version to 34 to be compatible with the new compose dependencies
Fixes [MP-3005](https://rokt.atlassian.net/browse/MP-3005)
Fixing build errors with the new version of the native SDK
Tested locally

MP-3005 - Fix the build error with SDK 4.1.0-beta.1

---

.buildkite/release.pipeline.yml

Fix release pipeline BK aws-sm regions
Add regions

add regions to bk aws sm

---

README.md
Rokt.Widget/README.md
Rokt.Widget/android/build.gradle
Rokt.Widget/plugin/src/withRoktSDK.ts
RoktSampleApp/android/build.gradle

Updated the maven URL for Android SDK
Fixes [([issue](https://rokt.atlassian.net/browse/MP-3087))]
Tested locally, build passed

MP-3093 Update Maven URL

---

.buildkite/bin/update_sample_app.sh
.buildkite/release.pipeline.yml

No jira fix release pipeline xcode 15

---

Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
Rokt.Widget/ios/RNRoktWidget.m
Rokt.Widget/src/Rokt.tsx
RoktSampleApp/App.js

Add logging API for ReactNative
Fixes [MP-3378](https://rokt.atlassian.net/browse/MP-3378)
Add `setLoggingEnabled` API

MP-3378 - Add logging API in ReactNative

---

.cortex/catalog/react-native-sdk.yaml

Add cortex configuration metadata to the repository

MP-3478 - Add cortex config

---

.buildkite/pipeline.yml
.buildkite/release.pipeline.yml
Rokt.Widget/android/build.gradle
Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
Rokt.Widget/ios/RNRoktWidget.m
Rokt.Widget/rokt-react-native-sdk.podspec
Rokt.Widget/src/Rokt.tsx
Rokt.Widget/src/index.tsx
RoktSampleApp/ios/Podfile
RoktSampleApp/ios/Podfile.lock

Merging Rokt config changes to release branch.
Fixes [CI-92](https://rokt.atlassian.net/browse/CI-92)

[CI-92] Merge Config Changes

---

Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
Rokt.Widget/ios/RNRoktWidget.m

Casing was incorrect. Change was not added in previous PRs
Fixes [CI-164](https://rokt.atlassian.net/browse/CI-164)
Changed casing to lowercase
Tested locally

[CI-164] Fix Color Casing

---

.cortex/catalog/react-native-sdk.yaml

This PR is to update Cortex Team name.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-52))]

NI-52 update team name in cortex

---

RoktSampleApp/package.json

Fix the build error by using the pinned version of `react-native-toast-message`
Tested in buildkite build 

NoJira - Fix the build error by using the static version

---

Rokt.Widget/ios/RNRoktWidget.m
Rokt.Widget/package-lock.json
Rokt.Widget/package.json
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/package.json

- add missing patch to track React framework type
- update Rokt-Widget version to 4.6

Add missing iOS framework type

---

RoktSampleApp/android/app/src/androidTest/java/com/roktsampleapp/RoktWebViewUITest.java

Add the correct phone number in the attributes
Fix the E2E test
Tested locally

NoJira - Fix End To End test

---

Rokt.Widget/android/build.gradle
RoktSampleApp/android/app/build.gradle
RoktSampleApp/android/build.gradle
RoktSampleApp/ios/RoktSampleApp.xcodeproj/project.pbxproj
RoktSampleApp/ios/RoktSampleApp/AppDelegate.mm
RoktSampleApp/package.json

This PR is to update `namespace` in build.gradle for Android and also update the ReactNative version as iOS build was failing due to boost library. More details of [issue](https://github.com/facebook/react-native/issues/42180)
Fixes [([issue](https://rokt.atlassian.net/browse/NI-466))]

[NI-466] Add namespace binding and update React Native version

---

Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt

- add else in android event handling to handle missing switch case

handle missing switch case for android

---

.buildkite/pipeline.yml
Rokt.Widget/android/build.gradle
Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
Rokt.Widget/ios/RNRoktWidget.m
Rokt.Widget/ios/RoktEventManager.m
Rokt.Widget/rokt-react-native-sdk.podspec
Rokt.Widget/src/Rokt.tsx
RoktSampleApp/App.js
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/ios/RoktSampleApp.xcodeproj/project.pbxproj

This PR is to add support TYP Events in the SDK.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-760))]

NI-760 Add Support for TYP Events

---

.cortex/catalog/react-native-sdk.yaml
.github/CODEOWNERS
README.md
RoktSampleApp/README.md

Update CODEOWNERS and the cortex catalog to reflect the new team name

NoJira - Update ownership and team

---

Rokt.Widget/android/build.gradle
Rokt.Widget/android/src/main/AndroidManifest.xml
Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModuleImpl.kt
Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetPackage.kt
Rokt.Widget/plugin/tsconfig.tsbuildinfo
RoktSampleApp/.gitignore

Minor refactoring to support ReactNative new architecture in Android wrapper
Refactoring 

refactor: small fixes for Android New Architecture support

---

.gitignore
Rokt.Widget/ios/RNRoktWidget.h
Rokt.Widget/ios/RNRoktWidget.mm
Rokt.Widget/ios/RNRoktWidgetModuleProvider.mm
Rokt.Widget/ios/RoktEventManager.h
Rokt.Widget/ios/RoktNativeWidgetComponentView.h
Rokt.Widget/ios/RoktNativeWidgetComponentView.mm
Rokt.Widget/package.json
Rokt.Widget/rokt-react-native-sdk.podspec
Rokt.Widget/src/NativeRoktWidget.ts
Rokt.Widget/src/Rokt.tsx
Rokt.Widget/src/RoktNativeWidgetNativeComponent.ts
Rokt.Widget/src/rokt-embedded-view.android.tsx
Rokt.Widget/src/rokt-embedded-view.d.ts
Rokt.Widget/src/rokt-embedded-view.ios.tsx
Rokt.Widget/src/rokt-embedded-view.ts
RoktSampleApp/.gitignore
RoktSampleApp/ios/Podfile
RoktSampleApp/ios/Podfile.lock
RoktSampleApp/ios/RoktSampleApp.xcodeproj/project.pbxproj
RoktSampleApp/ios/RoktSampleApp/Info.plist

Add support for the new architecture in iOS React Native.
Fixes [SQDSDKS-7462](https://mparticle-eng.atlassian.net/browse/SQDSDKS-7462)
- Added TurboModule support for the new architecture in iOS React Native
- Added Fabric support for the new architecture in iOS React Native
- Use the codegen and generated classes and interfaces for the bridge

feat: Add iOS React Native new architecture support

---

.github/actions/build-ios/action.yml
CHANGELOG.md
Rokt.Widget/android/build.gradle
Rokt.Widget/rokt-react-native-sdk.podspec
RoktSampleApp/ios/Podfile.lock

Update the SDK versions
Updates the Rokt Native SDJ versions
Tested locally

chore: Update Rokt SDK versions to 4.11.0 for Android and 4.14.0 for iOS
