- Rokt.Widget/android/build.gradle
- Rokt.Widget/package-lock.json
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/ios/RoktSampleAppUITests/RoktSampleAppUITests.swift
- RoktSampleApp/package-lock.json
- RoktSampleApp/package.json
Updating Rokt iOS and Android SDK versions to 3.11.0
Fixes [MP-1976](https://rokt.atlassian.net/browse/MP-1976)
- Updated Android SDK version to 3.11.0
- Updated iOS SDK version to 3.11.0
- Updated React Native SDK version to 3.11.0
- Updated a broken UI test for iOS
Manually ran and verified both example apps with updated SDKs.
> [MP-1976] Update SDK versions to 3.11.0

- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/ios/Podfile.lock
Cherry-pick https://github.com/ROKT/rokt-sdk-react-native/pull/78 and other packaging changes
Fixes xcode warning: no rule to process file '/<project_path>/node_modules/@rokt/react-native-sdk/ios/RNRoktWidget.xcodeproj/project.pbxproj' of type 'text.pbxproject' for architecture 'arm64'
> MP-2041 - Fix podspec including non source files

- .circleci/config.yml
- Rokt.Widget/android/build.gradle
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
Updating Rokt React Native SDK version to 3.13.0
Fixes [MP-2070]
- Updated native SDK version to 3.13.0
- Updated React Native version to 3.13.0
Ran both sample apps
CircleCI build is failing because one of the docker images was updated and the version was not pinned in the config
> [MP-2070] Update sdk version to 3.13.0

- RoktSampleApp/android/app/src/main/AndroidManifest.xml
- RoktSampleApp/android/app/src/main/res/xml/network_security_config.xml
Change the RoktSampleApp's AndroidManifest settings and add a network_security_config. To allow the debugging using http proxy tools
Adding debug settings into the RoktSampleApp
Tested locally using Proxyman proxy
> NoJira - Add network-security-config for better debugging

- .buildkite/pipeline.yml
- Rokt.Widget/android/build.gradle
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
Updating React Native SDK to version 3.14.0
Updating all SDK version to 3.14.0
Ran sample apps
> [MP-2174] Update sdk versions to 3.14.0

- Rokt.Widget/ios/RNRoktWidget.m
- Rokt.Widget/src/index.tsx
Add ability for RN partner to send URL error reports
- Add `sendUrlFailure` method that forwards to iOS SDK sendUrlFailure
Tested locally (added error call to sample app and check diagnostics send)
https://github.com/ROKT/rokt-sdk-react-native/assets/122853726/0fb9c6c4-757f-42ad-b70e-d99ebd48f296
> add sendUrlFailure

- Rokt.Widget/src/rokt-embedded-view.ios.tsx
Apply the fix of https://github.com/ROKT/rokt-sdk-react-native/pull/95 to version 3.16.x
> Apply the fix for version 3.16.x

- Rokt.Widget/android/build.gradle
- Rokt.Widget/package-lock.json
- Rokt.Widget/package.json
- RoktSampleApp/package.json
Disabling generation of BuildConfig since it causes conflicts to due package naming.
- Disabled generating BuildConfig for Android
- Updated version to 3.15.2
- Tested build locally and BuildConfig was not generated for Debug and Release variants
- Build passed with known conflicting package
> [NO_JIRA] Disabling BuildConfig generation

- .buildkite/pipeline.yml
- Rokt.Widget/ios/RNRoktWidget.m
Build pipeline wasn't using pipefail so when xcodebuild failed the error code wasn't piped to xcpretty.
- Added pipefail to xcodebuild step
- Added missing parenthesis
Ran the sample app locally.
> [NO-JIRA] Fix iOS build

- Rokt.Widget/src/rokt-embedded-view.android.tsx
Corner radius on Android doesn't display properly because of the background being white instead of transparent.
Make embedded background transparent instead of white
Same was applied for iOS before
> [NO-JIRA] Make android embedded background transparent

- Rokt.Widget/src/index.tsx
The `Map` type is not passing attributes correctly to `execute`. It is also too restrictive and requires instantiation via `new Map()` instead of just creating an object. `Record` allows for js style objects like
```
const attributes = {
"email": "test@test.com"
}
```
and still enforces type safety.
- Changed `Map` to `Record`
Tested in a Typescript file.
> [NO-JIRA] Change Map to Record

- Rokt.Widget/src/index.tsx
Same as https://github.com/ROKT/rokt-sdk-react-native/pull/106 but for next legacy release - but making Record optional. 
Added `Record` as optional type to not break anything using `Map`.
Tested with Typescript file.
> [NO-JIRA] Add Record as optional

- Rokt.Widget/package.json
- Rokt.Widget/src/index.tsx
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
Instead of having one signature that allows `Map` and `Record`, deprecating the one using `Map` and creating an overload for the one using `Record` to make it clearer to not use `Map` but without removing it entirely since it's a breaking change.
Fixes [MP-2722](https://rokt.atlassian.net/browse/MP-2722)
- Deprecated signatures using `Map`
- Added signatures using `Record`
- Also fixed another issue with the placeholder type
- Updated to 3.15.6
Checked using a Typescript file that objects are accepted without error and the `Map` signature shows as deprecated.
> [MP-2722] Correct types

- .buildkite/bin/create_tag.sh
- .buildkite/bin/extract_dist_tag.sh
- .buildkite/bin/update_sample_app.sh
- .buildkite/bin/update_versions.sh
- .buildkite/pipeline.yml
- .buildkite/release.pipeline.yml
- Rokt.Widget/README_PUBLISHING.md
- RoktSampleApp/android/fastlane/Fastfile
Adding automated release pipeline. It works similar to the other pipelines. 
Fixes [MP-2598](https://rokt.atlassian.net/browse/MP-2598)
- Generate tag with updated native SDK versions and sample app
- Extracting semver label to use as npm dist tag so alpha, beta etc. can be released from the same pipeline.
Published an alpha: 
https://buildkite.com/rokt/react-native-sdk/builds/223
https://www.npmjs.com/package/@rokt/react-native-sdk/v/3.15.3-alpha.2/
> [MP-2598] Automated Pipeline

- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.java
Propagate the unload reason to ReactNative event stream
Fixes [MP-3168](https://rokt.atlassian.net/browse/MP-3168)
SDK callback changed
Tested locally
> MP-3168 - Add onUnload event reason in the callback

- .buildkite/pipeline.yml
- .buildkite/release.pipeline.yml
- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.java
`useDCUIInit` parameter has been removed from the native init method.
Remove the parameter and use the new method signature
Method signature update
Tested locally.
> NoJira - Update Rokt.init api signature for Android

- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
- Rokt.Widget/ios/RNRoktWidget.h
- Rokt.Widget/ios/RNRoktWidget.m
- Rokt.Widget/ios/RoktEventManager.h
- Rokt.Widget/ios/RoktEventManager.m
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/App.js
- RoktSampleApp/ios/Podfile.lock
* Subscribe to the events api and send them to RN events channel
* Use the Activity lifecycleScope for collecting the flow.
Fixes [MP-3269](https://rokt.atlassian.net/browse/MP-3269)
Implemented the events API
Tested locally
> MP-3269 - Consume `Rokt.events()` and propagate to RN context

- .buildkite/pipeline.yml
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
When the Activity is starting up, the React component initialization can happen before the activity resume. In this scenario the currentActivity provided by RN framework would be null.
* When the currentActivity is null, add a delay in calling the Rokt SDK init
Fixes [MP-3481](https://rokt.atlassian.net/browse/MP-3481)
Fix for the init failure scenario.
Tested locally by creating RN release apk
> MP-3481 - Fix the issue when init was called before activity resume

- .buildkite/pipeline.yml
- .buildkite/release.pipeline.yml
- Rokt.Widget/src/Rokt.tsx
- Rokt.Widget/src/index.tsx
Creating Typescript builder class for RoktConfig. Only dealing with the wrapper side in this PR, will wire up to native modules next into workstation branch.
Fixes [CI-92](https://rokt.atlassian.net/browse/CI-92)
- Added `RoktConfigBuilder`: used like `new RoktConfigBuilder().withColorMode(ColorMode.Dark).build()`
Tested in tsx file
> [CI-92] Rokt Config Wrapper

- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
- Rokt.Widget/src/Rokt.tsx
Adding native modules for Android RoktConfig.
Fixes [CI-137](https://rokt.atlassian.net/browse/CI-137)
- Add Android native module for RoktConfig
- Refactor execute
- Map string map to RoktConfig Builder
Tested with a layout in light mode with dark config and got dark layout
> [CI-137] Rokt Config Native Android Modules

- Rokt.Widget/ios/RNRoktWidget.h
- Rokt.Widget/package-lock.json
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
Need to refactor RCTBridgeModule to support Expo 44
The conditional import for RCTBridgeModule removed. 
Tested locally.
> Refactor RCTBridgeModule imports

- Rokt.Widget/android/build.gradle
- Rokt.Widget/plugin/src/withRoktSDK.ts
New Expo version templates are in kotlin.
Support kotlin MainApplication file in the Expo plugin and add the `RoktEmbeddedViewPackage` in the package registry.
Fixes [LAYOUT-1313](https://rokt.atlassian.net/browse/LAYOUT-1313)
Fix the Expo plugin and make it compatible with the latest version
Tested locally with Expo 52(kotlin) and Expo 46(java)
> LAYOUT-1313 - Fix Expo plugin and support kotlin

- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
- Rokt.Widget/ios/RNRoktWidget.m
- Rokt.Widget/ios/RoktEventManager.h
- Rokt.Widget/ios/RoktEventManager.m
- Rokt.Widget/package-lock.json
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
Listen for global SDK events in native Android and iOS wrappers Propagate events in `RoktEvents` stream
Fixes [LAYOUT-1330](https://rokt.atlassian.net/browse/LAYOUT-1330)
Init complete event
Tested locally
Android
https://github.com/user-attachments/assets/c8718351-ed8f-42a0-b04f-c4a7ae0cd310
iOS
https://github.com/user-attachments/assets/0cae37ea-7225-4987-afce-15b98f0728a7
> LAYOUT-1330 - Implement Init complete event in ReactNative wrapper

- RoktSampleApp/android/app/build.gradle
Since the Example app is using an old AGP plugin it is failing in D8 step for lifecycle-livedata-core.
Force the app to use 2.5.1
Error with version `2.8.3`
```
/lifecycle-livedata-core-2.8.3-runtime.jar: D8: java.lang.NullPointerException
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Failed to transform lifecycle-livedata-core-2.8.3.aar (androidx.lifecycle:lifecycle-livedata-core:2.8.3) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, …
```
> NoJira - Fix the version conflict issue

- Rokt.Widget/ios/RoktWidgetManager.m
- Rokt.Widget/package-lock.json
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/README.md
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
with cocoapods we generate a umbrella header `Rokt-Widget-umbrella.h` in the module map, with version 4.7, we now generate a new umbrella header `Rokt_Widget-Swift.h`.
Hence we have to update the header name.
cocoapods module map file `Example/Pods/Target Support Files/Rokt-Widget/Rokt-Widget.modulemap`:
```
framework module Rokt_Widget {
umbrella header "Rokt-Widget-umbrella.h"
export *
module * { export * }
}
```
Fixes [([issue](https://rokt.atlassian.net/browse/NI-360))]
- update umbrella header name
- update version to 4.7
> NoJira - update xcframework header file

- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
- Rokt.Widget/ios/RNRoktWidget.m
- Rokt.Widget/package-lock.json
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- Rokt.Widget/src/Rokt.tsx
- Rokt.Widget/src/index.tsx
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
* Add cache config support in ReactNative javascript layer.
* Change the native wrapper for Android and iOS to accept `cacheConfig` param from JS bridge.
* Pass cacheConfig to the native SDK(TODO: iOS)
Fixes [LAYOUT-1641](https://rokt.atlassian.net/browse/LAYOUT-1641)
Cache API support in ReactNative SDK
Tested locally
> LAYOUT-1641 - Add caching API support in ReactNative SDK

- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/AndroidManifest.xml
- Rokt.Widget/package-lock.json
- Rokt.Widget/package.json
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/ios/Podfile.lock
- RoktSampleApp/package.json
The new AGP plugin won't allow package attribute in the AndroidManifest.
Android build will fail if the project is using an incompatible AGP plugin
Fixes [LAYOUT-2177](https://rokt.atlassian.net/browse/LAYOUT-2177)
* Remove the package attribute from the SDK's AndroidManifest
* Correct the namespace in the build.gradle.
* Update SDK version
Tested the build locally and in CI env
> LAYOUT-2177 - Fix AndroidManifest package attribute

- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetModule.kt
- Rokt.Widget/ios/RoktEventManager.m
- Rokt.Widget/rokt-react-native-sdk.podspec
- RoktSampleApp/android/build.gradle
- RoktSampleApp/ios/Podfile.lock
Implement the `OpenUrl` event support
Fixes [LAYOUT-2196](https://rokt.atlassian.net/browse/LAYOUT-2196)
* Update Rokt SDK dependencies to version 4.9.0-alpha.1
* Implement the `OpenUrl` Event in iOS and Android wrappers and propagate it as a JS event through the events channel
Tested locally using stubbed DCUI json
**iOS**
https://github.com/user-attachments/assets/b5b59a78-6bf3-44ce-a9fc-cdff9641b7a6
**Android**
https://github.com/user-attachments/assets/2f5e8af1-bf49-46bd-b109-36983ad0cf1f
> LAYOUT-2196 - Add support for OpenUrl event

- CHANGELOG.md
- Rokt.Widget/android/build.gradle
- Rokt.Widget/android/src/main/AndroidManifest.xml
- Rokt.Widget/android/src/main/AndroidManifestNew.xml
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RNRoktWidgetPackage.kt
- Rokt.Widget/android/src/main/java/com/rokt/reactnativesdk/RoktEmbeddedViewPackage.kt
- Rokt.Widget/rokt-react-native-sdk.podspec
Fixes to make the SDK work with ReactNative version 0.69.x
Updated gradle and podspec
Tested locally
> fix: Update podspec and Gradle build for backward compatibility
